"""adiciona escala de plantao

Revision ID: 20ea5b90cf00
Revises: bd3fc02901ea
Create Date: 2026-07-22 19:17:02.918002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ea5b90cf00'
down_revision = 'bd3fc02901ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turnos_plantao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ministerio_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=True),
    sa.Column('recorrencia', sa.String(length=10), nullable=False),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ministerio_id'], ['ministerios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overrides_plantao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=False),
    sa.Column('membro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['membro_id'], ['escala_membros.id'], ),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos_plantao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turno_id', 'periodo', name='uq_override_turno_periodo')
    )
    op.create_table('plantao_notificacoes_enviadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=False),
    sa.Column('janela', sa.String(length=3), nullable=False),
    sa.Column('enviado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos_plantao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turno_id', 'periodo', 'janela', name='uq_notificacao_turno_periodo_janela')
    )
    op.create_table('turno_plantao_membros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('membro_id', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['membro_id'], ['escala_membros.id'], ),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos_plantao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTA: o autogenerate tambem detectou "add foreign key" em escala_membros.comunidade_id
    # e escalas.ministerio_id -- essas colunas ja existem (adicionadas via ALTER TABLE ADD
    # COLUMN em migrations antigas) mas nunca ganharam uma FK real no schema do SQLite
    # (so existem como db.ForeignKey no lado do model). Isso e schema drift PRE-EXISTENTE,
    # sem relacao com plantao -- removido daqui de proposito pra nao misturar uma mudanca
    # de risco (rebuild de tabela) numa migration que devia ser so create_table simples.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turno_plantao_membros')
    op.drop_table('plantao_notificacoes_enviadas')
    op.drop_table('overrides_plantao')
    op.drop_table('turnos_plantao')
    # ### end Alembic commands ###
