"""remove coluna ordem nao utilizada de escalas

Revision ID: 5eb4f005b564
Revises: 5f88209bb9c4
Create Date: 2026-07-22 08:41:21.707621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb4f005b564'
down_revision = '5f88209bb9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escalas', schema=None) as batch_op:
        batch_op.drop_column('ordem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escalas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordem', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
