"""adiciona escala rapida (grupos, funcoes, membros)

Revision ID: 9e9b5511e38e
Revises: cdb26526bcb4
Create Date: 2026-07-21 22:57:48.514693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9b5511e38e'
down_revision = 'cdb26526bcb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escala_grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('escala_membros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escala_funcoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('membro_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notificado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['escala_grupos.id'], ),
    sa.ForeignKeyConstraint(['membro_id'], ['escala_membros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('escala_funcoes')
    op.drop_table('escala_membros')
    op.drop_table('escala_grupos')
    # ### end Alembic commands ###
